### ISSUE TITLE
MINTmap v2.0 alpha installation

### ISSUE THREAD

**Issue by cavelandiah** [TJU-CMC-Org/MINTmap#7]
Hi there,

Following the installation instructions from the README.md file for the v2.0-alpha release, it’s currently not possible to install `MINTmap`. After creating the conda environment and executing: 

`pip install dist/MINTmap-2.0a0-py3-none-any.whl`

there appears to be an issue with the pip wheel:

```
Processing ./dist/MINTmap-2.0a0-py3-none-any.whl
Collecting Jinja2<3.0.0,>=2.11.2 (from MINTmap==2.0a0)
  Downloading Jinja2-2.11.3-py2.py3-none-any.whl.metadata (3.5 kB)
Collecting PyYAML<6.0.0,>=5.3.1 (from MINTmap==2.0a0)
  Downloading PyYAML-5.4.1.tar.gz (175 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [65 lines of output]
      running egg_info
      writing lib3/PyYAML.egg-info/PKG-INFO
      writing dependency_links to lib3/PyYAML.egg-info/dependency_links.txt
      writing top-level names to lib3/PyYAML.egg-info/top_level.txt
      Traceback (most recent call last):
        File "/home/userx/anaconda3/envs/snowflake/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
          ~~~~^^
        File "/home/userx/anaconda3/envs/snowflake/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ~~~~^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/userx/anaconda3/envs/snowflake/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-build-env-c_mxxpfc/overlay/lib/python3.13/site-packages/setuptools/build_meta.py", line 334, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-c_mxxpfc/overlay/lib/python3.13/site-packages/setuptools/build_meta.py", line 304, in _get_build_requires
          self.run_setup()
          ~~~~~~~~~~~~~~^^
        File "/tmp/pip-build-env-c_mxxpfc/overlay/lib/python3.13/site-packages/setuptools/build_meta.py", line 320, in run_setup
          exec(code, locals())
          ~~~~^^^^^^^^^^^^^^^^
        File "<string>", line 271, in <module>
        File "/tmp/pip-build-env-c_mxxpfc/overlay/lib/python3.13/site-packages/setuptools/__init__.py", line 117, in setup
          return distutils.core.setup(**attrs)
                 ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
        File "/tmp/pip-build-env-c_mxxpfc/overlay/lib/python3.13/site-packages/setuptools/_distutils/core.py", line 183, in setup
          return run_commands(dist)
        File "/tmp/pip-build-env-c_mxxpfc/overlay/lib/python3.13/site-packages/setuptools/_distutils/core.py", line 199, in run_commands
          dist.run_commands()
          ~~~~~~~~~~~~~~~~~^^
        File "/tmp/pip-build-env-c_mxxpfc/overlay/lib/python3.13/site-packages/setuptools/_distutils/dist.py", line 954, in run_commands
          self.run_command(cmd)
          ~~~~~~~~~~~~~~~~^^^^^
        File "/tmp/pip-build-env-c_mxxpfc/overlay/lib/python3.13/site-packages/setuptools/dist.py", line 994, in run_command
          super().run_command(command)
          ~~~~~~~~~~~~~~~~~~~^^^^^^^^^
        File "/tmp/pip-build-env-c_mxxpfc/overlay/lib/python3.13/site-packages/setuptools/_distutils/dist.py", line 973, in run_command
          cmd_obj.run()
          ~~~~~~~~~~~^^
        File "/tmp/pip-build-env-c_mxxpfc/overlay/lib/python3.13/site-packages/setuptools/command/egg_info.py", line 312, in run
          self.find_sources()
          ~~~~~~~~~~~~~~~~~^^
        File "/tmp/pip-build-env-c_mxxpfc/overlay/lib/python3.13/site-packages/setuptools/command/egg_info.py", line 320, in find_sources
          mm.run()
          ~~~~~~^^
        File "/tmp/pip-build-env-c_mxxpfc/overlay/lib/python3.13/site-packages/setuptools/command/egg_info.py", line 543, in run
          self.add_defaults()
          ~~~~~~~~~~~~~~~~~^^
        File "/tmp/pip-build-env-c_mxxpfc/overlay/lib/python3.13/site-packages/setuptools/command/egg_info.py", line 581, in add_defaults
          sdist.add_defaults(self)
          ~~~~~~~~~~~~~~~~~~^^^^^^
        File "/tmp/pip-build-env-c_mxxpfc/overlay/lib/python3.13/site-packages/setuptools/command/sdist.py", line 109, in add_defaults
          super().add_defaults()
          ~~~~~~~~~~~~~~~~~~~~^^
        File "/tmp/pip-build-env-c_mxxpfc/overlay/lib/python3.13/site-packages/setuptools/_distutils/command/sdist.py", line 238, in add_defaults
          self._add_defaults_ext()
          ~~~~~~~~~~~~~~~~~~~~~~^^
        File "/tmp/pip-build-env-c_mxxpfc/overlay/lib/python3.13/site-packages/setuptools/_distutils/command/sdist.py", line 323, in _add_defaults_ext
          self.filelist.extend(build_ext.get_source_files())
                               ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
        File "<string>", line 201, in get_source_files
        File "/tmp/pip-build-env-c_mxxpfc/overlay/lib/python3.13/site-packages/setuptools/_distutils/cmd.py", line 107, in __getattr__
          raise AttributeError(attr)
      AttributeError: cython_sources
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

Do I miss something? Thanks in advance for your help.

**Comment by phillipeloher** [comment]
Hello,
We have seen something like that before.  Do you mind trying to revert PyYAML to version  5.3.1 and then reinstall the WHL?  If that helps, we will try to fix shortly.
